# Default Config
program_name: QSnippet
version: "0.0.8-dev"
log_level: ERROR

support_info:
  email: admin@quynnbell.com
  site: https://qsnippet.com

vault:
  salt: ""
  verifier: ""
  unlock_on_launch: false
  auto_lock_minutes: 15

images:
  icon_128: "icon_128x128.png"
  icon_64: "icon_64x64.png"
  icon_32: "icon_32x32.png"
  icon_16: "icon_16x16.png"
  icon: "QSnippet"
  snail: "snail.jpg"
  cat: "cat.jpg"